"""added username

Revision ID: 828727fed15d
Revises: 5e0706a5b895
Create Date: 2026-03-25 17:52:02.035437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828727fed15d'
down_revision = '5e0706a5b895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
